apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Denys Revutskyi backstage.
  links:
    - url: https://example.com/alert
      title: Alerts
      icon: alert
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
